### ISSUE TITLE
Feature - Calendar Component

### ISSUE THREAD

**Issue by emlez** [Platzi-Master-C8/gethired-jobplacement-salaries-frontend#3]
## Checklist ✅

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/Platzi-Master-C8/gethired-base/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

As a Company User I want to be able to schedule a meeting to carry out the negotiation that an Individual User is looking for, in order to agree on the platform and time of that meeting.

## Requirements 🌈

- Research libraries for the calendar
- Carry out a pilot test with the chosen schedule to verify that it meets the needs
- Implement calendar
- Consume API for calendar
- Implementation unit testing

## Motivation 🔦

In order to negotiate an initial offer, you should be able to schedule a meeting to discuss these matters.

**Comment by kevfarid** [comment]
Canceled
